// AUTO-GENERATED by scripts/generate-static-audio.mjs.
// Do not edit by hand. Re-run `npm run generate:static-audio` to update.
//
// Maps (voiceId, text) -> {audioUrl, alignmentUrl} for the hardcoded
// onboarding lines (welcome + scenes 1-8). Lines present here are served
// from public/voices/static/ instead of /api/tts (zero ElevenLabs cost).
// Lines NOT present (e.g. LLM-generated dialogue) fall back to live TTS.

export interface StaticAudioEntry {
  audioUrl: string;
  alignmentUrl: string;
}

export const STATIC_AUDIO_MANIFEST: Record<string, StaticAudioEntry> = {
  "052jzHJceQiZr7ltnY0C:Bag in the back. The bridge takes thirty minutes.": {
    "audioUrl": "/voices/static/0cb7ec6f058adc32.mp3",
    "alignmentUrl": "/voices/static/0cb7ec6f058adc32.json"
  },
  "052jzHJceQiZr7ltnY0C:I have three questions, and you owe me honest answers.": {
    "audioUrl": "/voices/static/23e6d0e0e8fe72c5.mp3",
    "alignmentUrl": "/voices/static/23e6d0e0e8fe72c5.json"
  },
  "052jzHJceQiZr7ltnY0C:I'm here because nobody else was going to drive at this hour.": {
    "audioUrl": "/voices/static/80288710cec8c1b6.mp3",
    "alignmentUrl": "/voices/static/80288710cec8c1b6.json"
  },
  "052jzHJceQiZr7ltnY0C:Jordan. Three years older on paper, ten in the head.": {
    "audioUrl": "/voices/static/fce841b9da03a39b.mp3",
    "alignmentUrl": "/voices/static/fce841b9da03a39b.json"
  },
  "052jzHJceQiZr7ltnY0C:What's the thing you don't say to investors?": {
    "audioUrl": "/voices/static/9f9d422809088986.mp3",
    "alignmentUrl": "/voices/static/9f9d422809088986.json"
  },
  "052jzHJceQiZr7ltnY0C:Who's in this with you, if anyone?": {
    "audioUrl": "/voices/static/d46b278fe0ba6b3b.mp3",
    "alignmentUrl": "/voices/static/d46b278fe0ba6b3b.json"
  },
  "052jzHJceQiZr7ltnY0C:Who's paying for the next 90 days?": {
    "audioUrl": "/voices/static/4f17a684cb2b508d.mp3",
    "alignmentUrl": "/voices/static/4f17a684cb2b508d.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:A few thousand people move to San Francisco every year to start a company.": {
    "audioUrl": "/voices/static/650f19db76e5e3ac.mp3",
    "alignmentUrl": "/voices/static/650f19db76e5e3ac.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:Before we get to the company, who are you?": {
    "audioUrl": "/voices/static/0faee4d76e2f5ef0.mp3",
    "alignmentUrl": "/voices/static/0faee4d76e2f5ef0.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:First-timer, second exit, somewhere weirder?": {
    "audioUrl": "/voices/static/815e3ab0809463c0.mp3",
    "alignmentUrl": "/voices/static/815e3ab0809463c0.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:Most become a story other founders tell at dinner.": {
    "audioUrl": "/voices/static/658c6262ac94fd02.mp3",
    "alignmentUrl": "/voices/static/658c6262ac94fd02.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:Most people stop here.": {
    "audioUrl": "/voices/static/6af6dcea9cbc1bfd.mp3",
    "alignmentUrl": "/voices/static/6af6dcea9cbc1bfd.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:Now the other one.": {
    "audioUrl": "/voices/static/14fc822ed94696c7.mp3",
    "alignmentUrl": "/voices/static/14fc822ed94696c7.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:One ticket. One direction. Non-refundable.": {
    "audioUrl": "/voices/static/4e8152221de47572.mp3",
    "alignmentUrl": "/voices/static/4e8152221de47572.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:Some of them become legends.": {
    "audioUrl": "/voices/static/d49f17a1b93c5ad2.mp3",
    "alignmentUrl": "/voices/static/d49f17a1b93c5ad2.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:That one I can't answer. Ask me something else about the city.": {
    "audioUrl": "/voices/static/eb82a67213133fe5.mp3",
    "alignmentUrl": "/voices/static/eb82a67213133fe5.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:The one with numbers. The one you'd say to a stranger sober.": {
    "audioUrl": "/voices/static/5507ebc062dc8e33.mp3",
    "alignmentUrl": "/voices/static/5507ebc062dc8e33.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:The rest of you become the story.": {
    "audioUrl": "/voices/static/1eec62013914c867.mp3",
    "alignmentUrl": "/voices/static/1eec62013914c867.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:Three sentences. Skip the deck voice.": {
    "audioUrl": "/voices/static/5e99e24e601bfb59.mp3",
    "alignmentUrl": "/voices/static/5e99e24e601bfb59.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:Tonight, you find out which.": {
    "audioUrl": "/voices/static/2819e6200972c024.mp3",
    "alignmentUrl": "/voices/static/2819e6200972c024.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:What are you building?": {
    "audioUrl": "/voices/static/98b16919158cb459.mp3",
    "alignmentUrl": "/voices/static/98b16919158cb459.json"
  },
  "6SMKBar4Q5wkVHdFlcQC:You've got a minute before the city gets its hooks in. Anything you want to ask before it does?": {
    "audioUrl": "/voices/static/c08791b7d0a8b2af.mp3",
    "alignmentUrl": "/voices/static/c08791b7d0a8b2af.json"
  }
};

export function staticAudioKey(voiceId: string, text: string): string {
  return `${voiceId}:${text}`;
}
